### ISSUE TITLE
request stay awaiting response with jinjs attached

### ISSUE THREAD

**Issue by panchicore** [ravelsoft/node-jinjs#17]
Hi, thanks for this project.
I tried to use it in a simple project to test the template inheritance (because express lacks of this feature).

this is my app.js: https://gist.github.com/1222305

but I dont get nothing, sever stay awaiting response.

What do you say? and thanks in advance.

**Comment by ceymard** [comment]
hi,

first, you ought to remove all the "pwilang" related stuff, as it is another project from jinjs, meant to be used with it, but which is right now only used by me and pretty undocumented.

second, your actual problem is with your use of express itself : the browser is "waiting..." because nothing is sent to it. Unlike traditional webapps (and Django), if you return something, this is _not_ sent to the client.

You have to use `res.write(my_template.render(context));`, but what you should _really_ do is remove the `require("layou...` line, and use the shortcut `res.render("layout.tpl", context);`.
