### ISSUE TITLE
npm istall jinjs 0.3.6 bug

### ISSUE THREAD

**Issue by piyagee** [ravelsoft/node-jinjs#26]
Hi

> require("jinjs")
> Error: Cannot find module 'jinjs'
>     at Function._resolveFilename (module.js:334:11)
>     at Function._load (module.js:279:25)
>     at Module.require (module.js:357:17)
>     at require (module.js:373:17)
>     at repl:1:2
>     at REPLServer.eval (repl.js:80:21)
>     at Interface.<anonymous> (repl.js:182:12)
>     at Interface.emit (events.js:67:17)
>     at Interface._onLine (readline.js:162:10)
>     at Interface._line (readline.js:426:8)

$ node -v
v0.6.9
$ npm -v
1.1.0-2

P.S. jinjs v 0.3.5 works fine

**Comment by ceymard** [comment]
You can install it from the github repo too.

The problem is with npm when I packaged. I thought I resolved it, but it would seem this package has been reverted to the buggy version (I did a --force when I saw the error) when the security problem happened.

I'll fix this ASAP, I don't have a computer I can do this with ATM.

**Comment by ceymard** [comment]
This should be fixed even in current 0.3.6 version. Sorry for the inconvenience.
